version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    networks:
      - be-bolsadetrabajo-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: be-bolsadetrabajo-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/schema-with-initial-data.sql:/docker-entrypoint-initdb.d/create_tables.sql
    command: --init-file /docker-entrypoint-initdb.d/create_tables.sql

  app:
    container_name: php_app
    networks:
      - be-bolsadetrabajo-network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: mysql
      DB_PASSWORD: 1234
      DB_HOST: mysql
      DB_NAME: be-bolsadetrabajo-db
      DB_PORT: 3306
      DEBUG: 1
      ENVIRONMENT: dev
      STORAGE_URL: /var/www/html/
      CONTAINER_NAME: uploads/
    ports:
      - "8080:80"
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    depends_on:
      - mysql

networks:
  be-bolsadetrabajo-network: