FROM node:latest

WORKDIR /usr/src/app

COPY test/e2e/package.json ./
COPY test/e2e/package*.json ./

RUN npm install

COPY test/e2e/ .

RUN apt-get update && apt-get install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb

RUN npm run cy:run