# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - bolsa-empleo
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v1

      - name: Configurar .env 
        run: |
          sed -i "s/\$DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g" .env
          sed -i "s/\$DB_NAME/${{ secrets.DB_NAME }}/g" .env
          sed -i "s/\$DB_HOST/${{ secrets.DB_HOST }}/g" .env
          sed -i "s/\$DB_USER/${{ secrets.DB_USER }}/g" .env
          sed -i "s/\$DB_PORT/${{ secrets.DB_PORT }}/g" .env
          cat .env
        

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/be-bolsa-empleo:latest .
        
      - name: Acceder al Registro de Contenedores
        run: echo ${{ secrets.CONTAINER_REGISTRY_TOKEN }} | docker login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.CONTAINER_REGISTRY_USER }} --password-stdin

      - name: Empujar la imagen al Registro de Contenedores
        run: |
          docker push ${{ secrets.CONTAINER_REGISTRY }}/be-bolsa-empleo:latest
