# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Production

on:
  workflow_dispatch:

jobs:
#  test-e2e:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build and run Docker containers
#        run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit

  build:
    runs-on: 'ubuntu-latest'
#    needs: test-e2e
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://bolsaempleouba.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4929bc3745254abb9a308f771c6c5c32 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_af512f8b3ff249ae80a21fc376c1e047 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: bolsaempleouba.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4929bc3745254abb9a308f771c6c5c32 }}/be-bolsa-empleo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bolsabeempleo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7fdfee7684e54a7cbd94597e9f32fafc }}
        images: 'bolsaempleouba.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4929bc3745254abb9a308f771c6c5c32 }}/be-bolsa-empleo:${{ github.sha }}'
